name: Update Skills

on:
  schedule:
    - cron: "45 */3 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  fetch:
    name: Fetch
    runs-on: ubuntu-latest
    outputs:
      shards: ${{ steps.shards.outputs.shards }}

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      # skills.sh api was gone
      # - run: pnpm command fetch skills.sh

      - run: pnpm command fetch skillsdirectory.com

      - uses: actions/upload-artifact@v6
        with:
          name: source-data
          path: data/source-*.json
          retention-days: 1

      - id: shards
        run: echo "shards=[$(seq -s', ' 1 256)]" >> $GITHUB_OUTPUT

  update:
    name: Update
    runs-on: ubuntu-latest
    needs: [fetch]
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJSON(needs.fetch.outputs.shards) }}

    steps:
      - uses: actions/checkout@v6

      - uses: nixbuild/nix-quick-install-action@v34

      - uses: actions/download-artifact@v7
        with:
          name: source-data
          path: data

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm command update ${{ matrix.shard }}/${{ strategy.job-total }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v6
        with:
          name: data-${{ matrix.shard }}
          path: data/shard/*.json
          retention-days: 1

  commit:
    name: Commit
    runs-on: ubuntu-latest
    needs: [update]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/download-artifact@v7
        with:
          name: source-data
          path: data

      - uses: actions/download-artifact@v7
        with:
          path: data/shard
          pattern: data-*
          merge-multiple: true

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm command combine

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "feat: update skills"
